/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CSourceWrapper : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CSourceWrapper(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CSourceWrapper obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CSourceWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigEnginePINVOKE.delete_CSourceWrapper(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CSourceWrapper(SWIGTYPE_p_ISoundSource source) : this(SwigEnginePINVOKE.new_CSourceWrapper(SWIGTYPE_p_ISoundSource.getCPtr(source)), true) {
  }

  public uint getPlayLength() {
    uint ret = SwigEnginePINVOKE.CSourceWrapper_getPlayLength(swigCPtr);
    return ret;
  }

}
